name: Deploy Docs to Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**
      - docs/**

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

# Disabled minification for now.   
      # - name: Install Lua
      #   uses: ljmf00/setup-lua@v1.0.0
      #   with:
      #     lua-version: 5.3
      #     install-luarocks: true
        
      # - name: Minify Scripts
      #   run: |
      #     script_dir=docs/src/.vuepress/public/scripts
      #     rm -rf $script_dir
      #     mkdir $script_dir
      #     lua minify.lua minify src/movescript.lua > $script_dir/movescript.lua
      #     lua minify.lua minify src/itemscript.lua > $script_dir/itemscript.lua
          
      # - name: Clean Up Lua Artifacts
      #   run: |
      #     rm -rf .lua
      #     rm -rf .luarocks
      #     rm -rf .source

      - name: Copy scripts to Docs public assets
        run: |
          script_dir=docs/src/.vuepress/public/scripts
          rm -rf $script_dir
          mkdir $script_dir
          cp src/* $script_dir/

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2
    
      - name: Install Dependencies
        working-directory: ./docs
        run: npm install
        
      - name: Build Static HTML Site
        working-directory: ./docs
        run: npm run build
        
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/src/.vuepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

